// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/stpnv0/SalesTracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockanalyticsService creates a new instance of mockanalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockanalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockanalyticsService {
	mock := &mockanalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockanalyticsService is an autogenerated mock type for the analyticsService type
type mockanalyticsService struct {
	mock.Mock
}

type mockanalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockanalyticsService) EXPECT() *mockanalyticsService_Expecter {
	return &mockanalyticsService_Expecter{mock: &_m.Mock}
}

// GetAnalytics provides a mock function for the type mockanalyticsService
func (_mock *mockanalyticsService) GetAnalytics(ctx context.Context, filter domain.AnalyticsFilter) (domain.AnalyticsResult, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 domain.AnalyticsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AnalyticsFilter) (domain.AnalyticsResult, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AnalyticsFilter) domain.AnalyticsResult); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(domain.AnalyticsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AnalyticsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsService_GetAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalytics'
type mockanalyticsService_GetAnalytics_Call struct {
	*mock.Call
}

// GetAnalytics is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.AnalyticsFilter
func (_e *mockanalyticsService_Expecter) GetAnalytics(ctx interface{}, filter interface{}) *mockanalyticsService_GetAnalytics_Call {
	return &mockanalyticsService_GetAnalytics_Call{Call: _e.mock.On("GetAnalytics", ctx, filter)}
}

func (_c *mockanalyticsService_GetAnalytics_Call) Run(run func(ctx context.Context, filter domain.AnalyticsFilter)) *mockanalyticsService_GetAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AnalyticsFilter
		if args[1] != nil {
			arg1 = args[1].(domain.AnalyticsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockanalyticsService_GetAnalytics_Call) Return(analyticsResult domain.AnalyticsResult, err error) *mockanalyticsService_GetAnalytics_Call {
	_c.Call.Return(analyticsResult, err)
	return _c
}

func (_c *mockanalyticsService_GetAnalytics_Call) RunAndReturn(run func(ctx context.Context, filter domain.AnalyticsFilter) (domain.AnalyticsResult, error)) *mockanalyticsService_GetAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// newMockexportItemService creates a new instance of mockexportItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockexportItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockexportItemService {
	mock := &mockexportItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockexportItemService is an autogenerated mock type for the exportItemService type
type mockexportItemService struct {
	mock.Mock
}

type mockexportItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockexportItemService) EXPECT() *mockexportItemService_Expecter {
	return &mockexportItemService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type mockexportItemService
func (_mock *mockexportItemService) List(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) ([]domain.Item, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) []domain.Item); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ItemFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.ItemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockexportItemService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockexportItemService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ItemFilter
func (_e *mockexportItemService_Expecter) List(ctx interface{}, filter interface{}) *mockexportItemService_List_Call {
	return &mockexportItemService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *mockexportItemService_List_Call) Run(run func(ctx context.Context, filter domain.ItemFilter)) *mockexportItemService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ItemFilter
		if args[1] != nil {
			arg1 = args[1].(domain.ItemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockexportItemService_List_Call) Return(items []domain.Item, n int64, err error) *mockexportItemService_List_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *mockexportItemService_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error)) *mockexportItemService_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockitemService creates a new instance of mockitemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockitemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockitemService {
	mock := &mockitemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockitemService is an autogenerated mock type for the itemService type
type mockitemService struct {
	mock.Mock
}

type mockitemService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockitemService) EXPECT() *mockitemService_Expecter {
	return &mockitemService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockitemService
func (_mock *mockitemService) Create(ctx context.Context, item domain.Item) (domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) (domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockitemService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.Item
func (_e *mockitemService_Expecter) Create(ctx interface{}, item interface{}) *mockitemService_Create_Call {
	return &mockitemService_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *mockitemService_Create_Call) Run(run func(ctx context.Context, item domain.Item)) *mockitemService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Item
		if args[1] != nil {
			arg1 = args[1].(domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemService_Create_Call) Return(item1 domain.Item, err error) *mockitemService_Create_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *mockitemService_Create_Call) RunAndReturn(run func(ctx context.Context, item domain.Item) (domain.Item, error)) *mockitemService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockitemService
func (_mock *mockitemService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockitemService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockitemService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockitemService_Expecter) Delete(ctx interface{}, id interface{}) *mockitemService_Delete_Call {
	return &mockitemService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mockitemService_Delete_Call) Run(run func(ctx context.Context, id string)) *mockitemService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemService_Delete_Call) Return(err error) *mockitemService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockitemService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockitemService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockitemService
func (_mock *mockitemService) GetByID(ctx context.Context, id string) (domain.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockitemService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockitemService_Expecter) GetByID(ctx interface{}, id interface{}) *mockitemService_GetByID_Call {
	return &mockitemService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockitemService_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockitemService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemService_GetByID_Call) Return(item domain.Item, err error) *mockitemService_GetByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Item, error)) *mockitemService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockitemService
func (_mock *mockitemService) List(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) ([]domain.Item, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) []domain.Item); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ItemFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.ItemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockitemService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockitemService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ItemFilter
func (_e *mockitemService_Expecter) List(ctx interface{}, filter interface{}) *mockitemService_List_Call {
	return &mockitemService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *mockitemService_List_Call) Run(run func(ctx context.Context, filter domain.ItemFilter)) *mockitemService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ItemFilter
		if args[1] != nil {
			arg1 = args[1].(domain.ItemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemService_List_Call) Return(items []domain.Item, n int64, err error) *mockitemService_List_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *mockitemService_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error)) *mockitemService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockitemService
func (_mock *mockitemService) Update(ctx context.Context, item domain.Item) (domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) (domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockitemService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.Item
func (_e *mockitemService_Expecter) Update(ctx interface{}, item interface{}) *mockitemService_Update_Call {
	return &mockitemService_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *mockitemService_Update_Call) Run(run func(ctx context.Context, item domain.Item)) *mockitemService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Item
		if args[1] != nil {
			arg1 = args[1].(domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemService_Update_Call) Return(item1 domain.Item, err error) *mockitemService_Update_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *mockitemService_Update_Call) RunAndReturn(run func(ctx context.Context, item domain.Item) (domain.Item, error)) *mockitemService_Update_Call {
	_c.Call.Return(run)
	return _c
}
