// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	"github.com/stpnv0/SalesTracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockanalyticsRepository creates a new instance of mockanalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockanalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockanalyticsRepository {
	mock := &mockanalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockanalyticsRepository is an autogenerated mock type for the analyticsRepository type
type mockanalyticsRepository struct {
	mock.Mock
}

type mockanalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockanalyticsRepository) EXPECT() *mockanalyticsRepository_Expecter {
	return &mockanalyticsRepository_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type mockanalyticsRepository
func (_mock *mockanalyticsRepository) Aggregate(ctx context.Context, from time.Time, to time.Time, itemType string) (domain.AnalyticsResult, error) {
	ret := _mock.Called(ctx, from, to, itemType)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 domain.AnalyticsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) (domain.AnalyticsResult, error)); ok {
		return returnFunc(ctx, from, to, itemType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) domain.AnalyticsResult); ok {
		r0 = returnFunc(ctx, from, to, itemType)
	} else {
		r0 = ret.Get(0).(domain.AnalyticsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string) error); ok {
		r1 = returnFunc(ctx, from, to, itemType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsRepository_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type mockanalyticsRepository_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - itemType string
func (_e *mockanalyticsRepository_Expecter) Aggregate(ctx interface{}, from interface{}, to interface{}, itemType interface{}) *mockanalyticsRepository_Aggregate_Call {
	return &mockanalyticsRepository_Aggregate_Call{Call: _e.mock.On("Aggregate", ctx, from, to, itemType)}
}

func (_c *mockanalyticsRepository_Aggregate_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, itemType string)) *mockanalyticsRepository_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockanalyticsRepository_Aggregate_Call) Return(analyticsResult domain.AnalyticsResult, err error) *mockanalyticsRepository_Aggregate_Call {
	_c.Call.Return(analyticsResult, err)
	return _c
}

func (_c *mockanalyticsRepository_Aggregate_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, itemType string) (domain.AnalyticsResult, error)) *mockanalyticsRepository_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateGrouped provides a mock function for the type mockanalyticsRepository
func (_mock *mockanalyticsRepository) AggregateGrouped(ctx context.Context, from time.Time, to time.Time, groupBy string, itemType string) ([]domain.GroupedAnalytics, error) {
	ret := _mock.Called(ctx, from, to, groupBy, itemType)

	if len(ret) == 0 {
		panic("no return value specified for AggregateGrouped")
	}

	var r0 []domain.GroupedAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string, string) ([]domain.GroupedAnalytics, error)); ok {
		return returnFunc(ctx, from, to, groupBy, itemType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string, string) []domain.GroupedAnalytics); ok {
		r0 = returnFunc(ctx, from, to, groupBy, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GroupedAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string, string) error); ok {
		r1 = returnFunc(ctx, from, to, groupBy, itemType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsRepository_AggregateGrouped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateGrouped'
type mockanalyticsRepository_AggregateGrouped_Call struct {
	*mock.Call
}

// AggregateGrouped is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - groupBy string
//   - itemType string
func (_e *mockanalyticsRepository_Expecter) AggregateGrouped(ctx interface{}, from interface{}, to interface{}, groupBy interface{}, itemType interface{}) *mockanalyticsRepository_AggregateGrouped_Call {
	return &mockanalyticsRepository_AggregateGrouped_Call{Call: _e.mock.On("AggregateGrouped", ctx, from, to, groupBy, itemType)}
}

func (_c *mockanalyticsRepository_AggregateGrouped_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, groupBy string, itemType string)) *mockanalyticsRepository_AggregateGrouped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockanalyticsRepository_AggregateGrouped_Call) Return(groupedAnalyticss []domain.GroupedAnalytics, err error) *mockanalyticsRepository_AggregateGrouped_Call {
	_c.Call.Return(groupedAnalyticss, err)
	return _c
}

func (_c *mockanalyticsRepository_AggregateGrouped_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, groupBy string, itemType string) ([]domain.GroupedAnalytics, error)) *mockanalyticsRepository_AggregateGrouped_Call {
	_c.Call.Return(run)
	return _c
}

// newMockitemRepository creates a new instance of mockitemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockitemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockitemRepository {
	mock := &mockitemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockitemRepository is an autogenerated mock type for the itemRepository type
type mockitemRepository struct {
	mock.Mock
}

type mockitemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockitemRepository) EXPECT() *mockitemRepository_Expecter {
	return &mockitemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Create(ctx context.Context, item domain.Item) (domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) (domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockitemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.Item
func (_e *mockitemRepository_Expecter) Create(ctx interface{}, item interface{}) *mockitemRepository_Create_Call {
	return &mockitemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *mockitemRepository_Create_Call) Run(run func(ctx context.Context, item domain.Item)) *mockitemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Item
		if args[1] != nil {
			arg1 = args[1].(domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_Create_Call) Return(item1 domain.Item, err error) *mockitemRepository_Create_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *mockitemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, item domain.Item) (domain.Item, error)) *mockitemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockitemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockitemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockitemRepository_Expecter) Delete(ctx interface{}, id interface{}) *mockitemRepository_Delete_Call {
	return &mockitemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mockitemRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *mockitemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_Delete_Call) Return(err error) *mockitemRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockitemRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockitemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) GetAll(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) ([]domain.Item, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ItemFilter) []domain.Item); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ItemFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.ItemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockitemRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockitemRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ItemFilter
func (_e *mockitemRepository_Expecter) GetAll(ctx interface{}, filter interface{}) *mockitemRepository_GetAll_Call {
	return &mockitemRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filter)}
}

func (_c *mockitemRepository_GetAll_Call) Run(run func(ctx context.Context, filter domain.ItemFilter)) *mockitemRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ItemFilter
		if args[1] != nil {
			arg1 = args[1].(domain.ItemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_GetAll_Call) Return(items []domain.Item, n int64, err error) *mockitemRepository_GetAll_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *mockitemRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, filter domain.ItemFilter) ([]domain.Item, int64, error)) *mockitemRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) GetByID(ctx context.Context, id string) (domain.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockitemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockitemRepository_Expecter) GetByID(ctx interface{}, id interface{}) *mockitemRepository_GetByID_Call {
	return &mockitemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockitemRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *mockitemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_GetByID_Call) Return(item domain.Item, err error) *mockitemRepository_GetByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *mockitemRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Item, error)) *mockitemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockitemRepository
func (_mock *mockitemRepository) Update(ctx context.Context, item domain.Item) (domain.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) (domain.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Item) domain.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockitemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockitemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item domain.Item
func (_e *mockitemRepository_Expecter) Update(ctx interface{}, item interface{}) *mockitemRepository_Update_Call {
	return &mockitemRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *mockitemRepository_Update_Call) Run(run func(ctx context.Context, item domain.Item)) *mockitemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Item
		if args[1] != nil {
			arg1 = args[1].(domain.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockitemRepository_Update_Call) Return(item1 domain.Item, err error) *mockitemRepository_Update_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *mockitemRepository_Update_Call) RunAndReturn(run func(ctx context.Context, item domain.Item) (domain.Item, error)) *mockitemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
